export enum types {
  TYPE_ADD_PRODUCT = "TYPE_ADD_PRODUCT",
  TYPE_DELETE_CART = "TYPE_DELETE_CART",
  TYPE_INCREMENT_CART = "TYPE_INCREMENT_CART",
  TYPE_DECREMENT_CART = "TYPE_DECREMENT_CART",
  TYPE_ADD_CART = "TYPE_ADD_CART",
  TYPE_CLEAN_CART = "TYPE_CLEAN_CART",
}